### ISSUE TITLE
Grey text too dim on light theme UIs

### ISSUE THREAD

**Issue by bbappserver** [Kazuwuqt/Anki_More_Overview_Stats#5]
<img width="389" alt="image" src="https://user-images.githubusercontent.com/27609692/164992322-961abaaf-3148-41d0-a846-9af48dcbce13.png">

While still technically legible it is quite difficult to read the text at the bottom.

**Comment by patrick-mahnkopf** [comment]
Hey, thanks for reporting this.

You can customize the colors through the config. Please check the [add-on page](https://ankiweb.net/shared/info/738807903) on how to do that.
In your case, you'll want to change the “Total”, “Days until done”, and “Done on Date” fields from “#ddd” to a color that's easier to read with your setup.
You can find colors you like on websites like [this one](https://htmlcolorcodes.com/), a possible fit might be something like “#222222”.

Hope this helps, and thank you for using the add-on.
