### ISSUE TITLE
Doesn't show on completed decks anymore after new update

### ISSUE THREAD

**Issue by chiascuro** [Kazuwuqt/Anki_More_Overview_Stats#9]
See title.

Completed deck:
![image](https://github.com/user-attachments/assets/cabb8dd2-b8cb-448d-b959-a07a3e9fa03d)

Config: (show for finished is set to true)
![image](https://github.com/user-attachments/assets/65c64836-a7eb-4d54-9cd1-3934f0e446c8)

**Comment by patrick-mahnkopf** [comment]
Hey there!
I seem to have broken the add-on for Anki versions 2.1.49 and older in yesterday's update, sorry for that!
I have uploaded a new version that should fix the add-on for all Anki versions.
Please let me know if you continue to have issues.

**Comment by chiascuro** [comment]
Thank you, it works again!
